name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    secrets:
      - db_password
      - credentials
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    depends_on:
      - wordpress

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mahkilic/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mahkilic/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
